Breadcrumbs
DFE-Digital/get-a-teacher-relocation-payment pull request #141
Opened 2023-07-07 14:43 UTC by raul-gracia

## Description
Adding breadcrumbs for the application view and update progress form

## Trello Card Link

https://trello.com/c/xm3uDtUz

2023-07-07 14:43 UTC, raul-gracia commented
![](https://github.trello.services/images/mini-trello-icon.png) [Applications List: Add breadcrumbs](https://trello.com/c/xm3uDtUz/130-applications-list-add-breadcrumbs)

2023-07-11 07:52 UTC, padv2010 requested changes
We don't have tests to make sure that navigation via Breadcrumbs works
as expected. Also, as we don't have tests for the update progress path (which
looks like technical debt) we are not exercising that code which can make it fail
in production.

2023-07-14 13:52 UTC, raul-gracia commented
I don't consider the breadcrumbs to have any logic worth testing. The code only adds 2 extra links.
As per the update progress form that has no tests, that is not part of this PR and shouldn't be discussed here.

2023-07-14 16:44 UTC, padv2010 commented
> I don't consider the breadcrumbs to have any logic worth testing. The code only adds 2 extra links.

Testing navigation is important for many reasons:

1. Guarantee that this works in production. Breadcrumbs will grow with the application, and will enable editing, deleting, reporting and many other functionalities. 
2. Makes refactoring possible, which is one of the main goals of having a test suite. Who wants to refactor a route and then check manually that all the application breadcrumbs still navigates as expected.
3. Guarantee that changes in the routes won't make breadcrumb navigation fail.

> As per the update progress form that has no tests, that is not part of this PR and shouldn't be discussed here.

Quite the opposite. This is the right place for discussing the  lack of system tests for the `update report` page. 
Have a look how all tests pass even when the breadcrumbs break the application in production for the `update` page:

```
<%= content_for(:breadcrumbs) do %>
  <%= govuk_breadcrumbs(breadcrumbs: [
    govuk_breadcrumb_link_to("Applications", applicants_path),
    govuk_breadcrumb_link_to(@applicant.full_name, applicant_path(@applicant)),
   ** raise "Update Progress" **
  ]) %>
<% end %>
```

We have a green build, which means, that Admins would be unable to use the application input production.
Should we have a feature test for the `update progress` page, at least, you would cover agents from receiving a 500 error when visiting the page.

This is why I mentioned the `update` system test. As a way to alleviate the fact that we have 0 tests covering breadcrumbs.

As a side note, it takes more time, to discuss this, than adding a two lines test for the breadcrumbs :(

As there seem to be some urgency into merging this, I would suggest reaching out to @duncanjbrown in case this has to be merged.

2023-07-17 14:27 UTC, duncanjbrown approved these changes
I understand that there's some urgency here so I'm not going to block this, but Pablo's right about it being a significant risk when there's an altogether untested page in the app — please do rectify that in another PR.

2023-07-17 15:50 UTC, raul-gracia commented on app/views/system_admin/applicants/edit.html.erb
> +    govuk_breadcrumb_link_to("Update Progress", "#")
Not really. I've updated both views to include a text version instead of a link for the last item on the breadcrumbs.

2023-07-17 23:33 UTC, merged